---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-nfs-share
  namespace: stage
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.1.111
    path: /var/nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileshare
  namespace: stage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
